#!/usr/bin/env sh

# Unmount and power off disk

#sync && udisksctl unmount -b /dev/sdb1 && udisksctl power-off -b /dev/sdb1

sync;
disk=$(df -H | sed 1d | eval "fzf $FZF_DEFAULT_OPTS" | awk '{print $1}')
udisksctl unmount -b $disk;
if [ $? -eq 0 ]; then
  udisksctl power-off -b $disk
  if [ $? -eq 0 ]; then
    echo "$disk power off"
  fi
fi
