#!/bin/env sh

case "$1" in
    lock)
        betterlockscreen -l dimblur
        ;;
    logout)
        pkill -KILL -u $USER
        ;;
    switch_user)
        dm-tool switch-to-greeter
        ;;
    suspend)
        systemctl suspend
        ;;
    hibernate)
        systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        exit 2
esac

exit 0
